adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Product image 1.png
adx_parentpageid: bb6be0c6-7d47-ed11-bba3-002248627c71
adx_partialurl: Product image 1.png
adx_publishingstateid: 656be0c6-7d47-ed11-bba3-002248627c71
adx_webfileid: a96be0c6-7d47-ed11-bba3-002248627c71
annotationid: 5f29eecc-7d47-ed11-bba3-002248627c71
filename: Product image 1.png
isdocument: true
mimetype: image/png
objectid: a96be0c6-7d47-ed11-bba3-002248627c71
objecttypecode: adx_webfile
